name = "laplace"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["Laplace"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.29.0"

[[require]]
name = "Threepoint"
git = "https://github.com/timaeus-research/threepoint"
rev = "40398d8"

[[lean_lib]]
name = "Laplace"
