/-
Copyright (c) 2026 Daniel Murfet. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Daniel Murfet
-/
import Laplace.Grammar.MonomialShiftedMoments
import Mathlib.Topology.Algebra.MvPolynomial

/-!
# Continuous test functions from monomial moments

Second step of the continuous-amplitude milestone (Astra #16, route C), independent of the
Laplace-specific constants. On the closed unit cube `K = [0,1]^d`:

* **polynomial density** (`exists_mvPolynomial_near`): every continuous `η` is uniformly
  approximated on `K` by the evaluation of a multivariate polynomial — Stone–Weierstrass for the
  subalgebra of `C(ℝ^d, ℝ)` generated by the coordinate functions, whose elements are exactly the
  polynomial functions (`mem_coordAlgebra_eval`);
* **moment transfer** (`tendsto_integral_of_monomials`): for nonnegative integrable weights `w_N`,
  `w_L` on a set `S ⊆ K` and maps `φ_N`, `φ_L` sending `S` into `K`, if
  `∫_S (φ_N x)^γ w_N(x) dx → ∫_S (φ_∞ x)^γ w_∞(x) dx` for every monomial `x^γ`, then
  `∫_S η(φ_N x) w_N(x) dx → ∫_S η(φ_∞ x) w_∞(x) dx` for every continuous `η`. The proof is the
  standard `ε/3` argument: the constant monomial gives an eventual mass bound, polynomials converge
  by finite linearity, and positivity turns a uniform polynomial approximation into an integral bound.

The maps `φ` allow the limiting functional to be supported on a face (`φ_L` = projection killing the
minimal coordinates) while the finite-`N` functionals use `φ_N = id`.
-/

open MeasureTheory Set Filter Topology

namespace Laplace.Grammar

/-- The closed unit cube `[0,1]^d`. -/
def closedCube (d : ℕ) : Set (Fin d → ℝ) := Set.pi univ fun _ => Icc (0 : ℝ) 1

theorem isCompact_closedCube (d : ℕ) : IsCompact (closedCube d) :=
  isCompact_univ_pi fun _ => isCompact_Icc

theorem unitBox_subset_closedCube (d : ℕ) : unitBox d ⊆ closedCube d :=
  pi_mono fun _ _ => Ioc_subset_Icc_self

/-- The subalgebra of `C(ℝ^d, ℝ)` generated by the coordinate functions. -/
noncomputable def coordAlgebra (d : ℕ) : Subalgebra ℝ C(Fin d → ℝ, ℝ) :=
  Algebra.adjoin ℝ (Set.range fun i : Fin d => (ContinuousMap.eval i : C(Fin d → ℝ, ℝ)))

theorem coordAlgebra_separatesPoints (d : ℕ) : (coordAlgebra d).SeparatesPoints := by
  intro x y hxy
  obtain ⟨i, hi⟩ := Function.ne_iff.1 hxy
  exact ⟨_, ⟨ContinuousMap.eval i, Algebra.subset_adjoin ⟨i, rfl⟩, rfl⟩, hi⟩

/-- Elements of the coordinate algebra are polynomial functions. -/
theorem mem_coordAlgebra_eval (d : ℕ) {g : C(Fin d → ℝ, ℝ)} (hg : g ∈ coordAlgebra d) :
    ∃ p : MvPolynomial (Fin d) ℝ, ∀ x, g x = MvPolynomial.eval x p := by
  unfold coordAlgebra at hg
  induction hg using Algebra.adjoin_induction with
  | mem g hg =>
    obtain ⟨i, rfl⟩ := hg
    exact ⟨MvPolynomial.X i, fun x => by simp⟩
  | algebraMap r => exact ⟨MvPolynomial.C r, fun x => by simp⟩
  | add g₁ g₂ _ _ ih₁ ih₂ =>
    obtain ⟨p₁, hp₁⟩ := ih₁
    obtain ⟨p₂, hp₂⟩ := ih₂
    exact ⟨p₁ + p₂, fun x => by simp [hp₁, hp₂]⟩
  | mul g₁ g₂ _ _ ih₁ ih₂ =>
    obtain ⟨p₁, hp₁⟩ := ih₁
    obtain ⟨p₂, hp₂⟩ := ih₂
    exact ⟨p₁ * p₂, fun x => by simp [hp₁, hp₂]⟩

/-- **Polynomial density on the cube**. -/
theorem exists_mvPolynomial_near (d : ℕ) (η : (Fin d → ℝ) → ℝ) (hη : Continuous η) (ε : ℝ)
    (hε : 0 < ε) :
    ∃ p : MvPolynomial (Fin d) ℝ, ∀ x ∈ closedCube d, |η x - MvPolynomial.eval x p| < ε := by
  obtain ⟨g, hgA, hg⟩ :=
    ContinuousMap.exists_mem_subalgebra_near_continuous_of_isCompact_of_separatesPoints
      (coordAlgebra_separatesPoints d) ⟨η, hη⟩ (isCompact_closedCube d) hε
  obtain ⟨p, hp⟩ := mem_coordAlgebra_eval d hgA
  refine ⟨p, fun x hx => ?_⟩
  have := hg x hx
  simp only [Real.norm_eq_abs, ContinuousMap.coe_mk, hp x] at this
  rwa [abs_sub_comm]

/-- An `ε/3` lemma: a function approximated eventually within `ε` by convergent functions whose
limits are within `ε` of `a` converges to `a`. -/
theorem tendsto_of_approx (f : ℝ → ℝ) (a : ℝ)
    (h : ∀ ε > 0, ∃ g : ℝ → ℝ, ∃ b : ℝ, Tendsto g atTop (𝓝 b) ∧
      (∀ᶠ N in atTop, |f N - g N| ≤ ε) ∧ |a - b| ≤ ε) :
    Tendsto f atTop (𝓝 a) := by
  rw [Metric.tendsto_atTop]
  intro ε hε
  obtain ⟨g, b, hg, hfg, hab⟩ := h (ε / 3) (by positivity)
  obtain ⟨N₁, hN₁⟩ := Metric.tendsto_atTop.1 hg (ε / 3) (by positivity)
  obtain ⟨N₂, hN₂⟩ := eventually_atTop.1 hfg
  refine ⟨max N₁ N₂, fun N hN => ?_⟩
  have h1 := hN₁ N (le_of_max_le_left hN)
  have h2 := hN₂ N (le_of_max_le_right hN)
  rw [Real.dist_eq] at h1 ⊢
  calc |f N - a| = |(f N - g N) + (g N - b) + (b - a)| := by ring_nf
    _ ≤ |f N - g N| + |g N - b| + |b - a| := abs_add_three _ _ _
    _ < ε := by rw [abs_sub_comm b a]; linarith

/-- Continuous functions of a cube-valued map times an integrable weight are integrable. -/
theorem integrableOn_comp_mul_of_continuous (d : ℕ) (S : Set (Fin d → ℝ)) (hS : MeasurableSet S)
    (φ : (Fin d → ℝ) → (Fin d → ℝ)) (hφ : MapsTo φ S (closedCube d)) (hφm : Measurable φ)
    (w : (Fin d → ℝ) → ℝ) (hw : IntegrableOn w S) (f : (Fin d → ℝ) → ℝ) (hf : Continuous f) :
    IntegrableOn (fun x => f (φ x) * w x) S := by
  obtain ⟨C, hC⟩ := (isCompact_closedCube d).exists_bound_of_continuousOn hf.continuousOn
  refine Integrable.mono' (hw.norm.const_mul C)
    ((hf.measurable.comp hφm).aestronglyMeasurable.mul hw.aestronglyMeasurable) ?_
  refine (ae_restrict_iff' hS).2 (Eventually.of_forall fun x hx => ?_)
  rw [norm_mul]
  exact mul_le_mul_of_nonneg_right (hC _ (hφ hx)) (norm_nonneg _)

theorem continuous_monomial (d : ℕ) (γ : Fin d → ℕ) :
    Continuous fun y : Fin d → ℝ => ∏ i, y i ^ γ i :=
  continuous_finsetProd _ fun i _ => (continuous_apply i).pow _

/-- Polynomial test functions: the weighted integral is the finite sum of monomial moments. -/
theorem integral_eval_mul_eq_sum (d : ℕ) (S : Set (Fin d → ℝ)) (hS : MeasurableSet S)
    (φ : (Fin d → ℝ) → (Fin d → ℝ)) (hφ : MapsTo φ S (closedCube d)) (hφm : Measurable φ)
    (w : (Fin d → ℝ) → ℝ) (hw : IntegrableOn w S) (p : MvPolynomial (Fin d) ℝ) :
    ∫ x in S, MvPolynomial.eval (φ x) p * w x =
      ∑ γ ∈ p.support, MvPolynomial.coeff γ p * ∫ x in S, (∏ i, φ x i ^ γ i) * w x := by
  simp_rw [MvPolynomial.eval_eq', Finset.sum_mul, mul_assoc]
  rw [integral_finsetSum _ fun (γ : Fin d →₀ ℕ) _ =>
    (integrableOn_comp_mul_of_continuous d S hS φ hφ hφm w hw _
      (continuous_monomial d fun i => γ i)).const_mul (MvPolynomial.coeff γ p)]
  exact Finset.sum_congr rfl fun γ _ => integral_const_mul _ _

/-- **Moment transfer on the cube**: monomial convergence of nonnegative weighted functionals (with
an eventual mass bound supplied by the constant monomial) implies convergence against every
continuous test function. -/
theorem tendsto_integral_of_monomials (d : ℕ) (S : Set (Fin d → ℝ)) (hS : MeasurableSet S)
    (φ : ℝ → (Fin d → ℝ) → (Fin d → ℝ)) (φL : (Fin d → ℝ) → (Fin d → ℝ))
    (hφ : ∀ N, MapsTo (φ N) S (closedCube d)) (hφL : MapsTo φL S (closedCube d))
    (hφm : ∀ N, Measurable (φ N)) (hφLm : Measurable φL)
    (w : ℝ → (Fin d → ℝ) → ℝ) (wL : (Fin d → ℝ) → ℝ)
    (hw : ∀ N, IntegrableOn (w N) S) (hwL : IntegrableOn wL S)
    (hwnn : ∀ N, ∀ x ∈ S, 0 ≤ w N x) (hwLnn : ∀ x ∈ S, 0 ≤ wL x)
    (hmono : ∀ γ : Fin d → ℕ, Tendsto (fun N => ∫ x in S, (∏ i, φ N x i ^ γ i) * w N x) atTop
      (𝓝 (∫ x in S, (∏ i, φL x i ^ γ i) * wL x)))
    (η : (Fin d → ℝ) → ℝ) (hη : Continuous η) :
    Tendsto (fun N => ∫ x in S, η (φ N x) * w N x) atTop (𝓝 (∫ x in S, η (φL x) * wL x)) := by
  -- eventual mass bound from the constant monomial
  have hmass := hmono (fun _ => 0)
  simp only [pow_zero, Finset.prod_const_one, one_mul] at hmass
  set M := ∫ x in S, wL x with hM
  have hMnn : 0 ≤ M := setIntegral_nonneg hS hwLnn
  have hB : ∀ᶠ N in atTop, ∫ x in S, w N x ≤ M + 1 :=
    (hmass.eventually (gt_mem_nhds (by linarith : M < M + 1))).mono fun _ h => h.le
  -- polynomial test functions
  have hpoly : ∀ p : MvPolynomial (Fin d) ℝ,
      Tendsto (fun N => ∫ x in S, MvPolynomial.eval (φ N x) p * w N x) atTop
        (𝓝 (∫ x in S, MvPolynomial.eval (φL x) p * wL x)) := by
    intro p
    rw [integral_eval_mul_eq_sum d S hS φL hφL hφLm wL hwL p]
    refine (tendsto_finsetSum _ fun (γ : Fin d →₀ ℕ) _ =>
      (hmono fun i => γ i).const_mul (MvPolynomial.coeff γ p)).congr fun N => ?_
    exact (integral_eval_mul_eq_sum d S hS (φ N) (hφ N) (hφm N) (w N) (hw N) p).symm
  -- the `ε/3` argument
  refine tendsto_of_approx _ _ fun ε hε => ?_
  set δ : ℝ := ε / (M + 2) with hδ
  have hδpos : 0 < δ := by positivity
  obtain ⟨p, hp⟩ := exists_mvPolynomial_near d η hη δ hδpos
  have hbound : ∀ (ψ : (Fin d → ℝ) → (Fin d → ℝ)) (v : (Fin d → ℝ) → ℝ),
      MapsTo ψ S (closedCube d) → Measurable ψ → IntegrableOn v S → (∀ x ∈ S, 0 ≤ v x) →
      |(∫ x in S, η (ψ x) * v x) - ∫ x in S, MvPolynomial.eval (ψ x) p * v x| ≤
        δ * ∫ x in S, v x := by
    intro ψ v hψ hψm hv hvnn
    rw [← integral_sub (integrableOn_comp_mul_of_continuous d S hS ψ hψ hψm v hv η hη)
      (integrableOn_comp_mul_of_continuous d S hS ψ hψ hψm v hv _ (MvPolynomial.continuous_eval p)),
      ← integral_const_mul, ← Real.norm_eq_abs]
    refine norm_integral_le_of_norm_le (hv.const_mul δ)
      ((ae_restrict_iff' hS).2 (Eventually.of_forall fun x hx => ?_))
    rw [← sub_mul, norm_mul, Real.norm_eq_abs, Real.norm_eq_abs, abs_of_nonneg (hvnn x hx)]
    exact mul_le_mul_of_nonneg_right (hp _ (hψ hx)).le (hvnn x hx)
  refine ⟨fun N => ∫ x in S, MvPolynomial.eval (φ N x) p * w N x,
    ∫ x in S, MvPolynomial.eval (φL x) p * wL x, hpoly p, ?_, ?_⟩
  · filter_upwards [hB] with N hN
    calc |(∫ x in S, η (φ N x) * w N x) - ∫ x in S, MvPolynomial.eval (φ N x) p * w N x|
        ≤ δ * ∫ x in S, w N x := hbound (φ N) (w N) (hφ N) (hφm N) (hw N) (hwnn N)
      _ ≤ δ * (M + 1) := by gcongr
      _ ≤ ε := by
          rw [hδ, div_mul_eq_mul_div, div_le_iff₀ (by positivity)]
          nlinarith
  · calc |(∫ x in S, η (φL x) * wL x) - ∫ x in S, MvPolynomial.eval (φL x) p * wL x|
        ≤ δ * M := hbound φL wL hφL hφLm hwL hwLnn
      _ ≤ ε := by
          rw [hδ, div_mul_eq_mul_div, div_le_iff₀ (by positivity)]
          nlinarith

end Laplace.Grammar
