/-
Copyright (c) 2026 Timaeus. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import Mathlib
import Laplace.Multi.MonomialTests

/-!
# Moment determinacy of compactly supported continuous densities

A continuous, compactly supported `f : ℝⁿ → ℝ` all of whose monomial moments `∫ xᵛ f` vanish
is zero (`eq_zero_of_integral_monomialTest_mul_eq_zero`). This is the Stone–Weierstrass theorem
applied to the subalgebra of `C(K, ℝ)`, `K = tsupport f`, generated by the coordinate functions:
it separates points, so it is dense; every element of it is the restriction of a polynomial
(the adjoin of the coordinates is the span `polySpan n` of all monomials, which is closed under
products since `xᵛ xʷ = x^{v ++ w}`), and `∫ P f = 0` for every polynomial `P` by linearity. Then
`∫ f² = ∫ f (f - P) ≤ ε ∫ |f|` for every `ε`, so `∫ f² = 0` and `f = 0` by continuity.

This is the tangential ingredient of the Morse–Bott normal form theorem: the tangential
moments of a compactly supported continuous density on the zero manifold determine it.
-/

open MeasureTheory

namespace Laplace.Multi

variable {n : ℕ}

/-! ### Polynomial functions -/

/-- All polynomial functions on `ℝⁿ`: the span of the monomials of every degree. -/
def polySpan (n : ℕ) : Submodule ℝ (EuclidD n → ℝ) :=
  Submodule.span ℝ (⋃ k : ℕ, Set.range (monomialTest : (Fin k → Fin n) → EuclidD n → ℝ))

theorem monomialTest_mem_polySpan {k : ℕ} (w : Fin k → Fin n) : monomialTest w ∈ polySpan n :=
  Submodule.subset_span (Set.mem_iUnion.mpr ⟨k, Set.mem_range_self w⟩)

theorem monomialTest_mul_monomialTest {k₁ k₂ : ℕ} (w₁ : Fin k₁ → Fin n) (w₂ : Fin k₂ → Fin n) :
    monomialTest w₁ * monomialTest w₂ = monomialTest (Fin.append w₁ w₂) := by
  funext x
  simp only [Pi.mul_apply, monomialTest]
  rw [Fin.prod_univ_add]
  simp [Fin.append_left, Fin.append_right]

theorem polySpan_mul_mem {P Q : EuclidD n → ℝ} (hP : P ∈ polySpan n) (hQ : Q ∈ polySpan n) :
    P * Q ∈ polySpan n := by
  have h := Submodule.mul_mem_mul hP hQ
  rw [polySpan, Submodule.span_mul_span] at h
  refine (Submodule.span_le.mpr ?_) h
  rintro _ ⟨a, ha, b, hb, rfl⟩
  obtain ⟨k₁, ⟨w₁, rfl⟩⟩ := Set.mem_iUnion.mp ha
  obtain ⟨k₂, ⟨w₂, rfl⟩⟩ := Set.mem_iUnion.mp hb
  change monomialTest w₁ * monomialTest w₂ ∈ (polySpan n : Set (EuclidD n → ℝ))
  rw [monomialTest_mul_monomialTest]
  exact monomialTest_mem_polySpan _

theorem continuous_of_mem_polySpan {P : EuclidD n → ℝ} (hP : P ∈ polySpan n) : Continuous P := by
  induction hP using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨k, ⟨w, rfl⟩⟩ := Set.mem_iUnion.mp hx
    exact monomialTest_continuous w
  | zero => exact continuous_const
  | add x y _ _ hx hy => exact hx.add hy
  | smul a x _ hx => exact hx.const_smul a

/-- Vanishing monomial moments give vanishing polynomial moments. -/
theorem integral_mul_eq_zero_of_mem_polySpan {f : EuclidD n → ℝ} (hf : Continuous f)
    (hsupp : HasCompactSupport f)
    (h : ∀ (k : ℕ) (w : Fin k → Fin n), ∫ y, monomialTest w y * f y = 0)
    {P : EuclidD n → ℝ} (hP : P ∈ polySpan n) : ∫ y, P y * f y = 0 := by
  induction hP using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨k, ⟨w, rfl⟩⟩ := Set.mem_iUnion.mp hx
    exact h k w
  | zero => simp
  | add x y hx' hy' hx hy =>
    have hxi : Integrable (fun z ↦ x z * f z) :=
      ((continuous_of_mem_polySpan hx').mul hf).integrable_of_hasCompactSupport hsupp.mul_left
    have hyi : Integrable (fun z ↦ y z * f z) :=
      ((continuous_of_mem_polySpan hy').mul hf).integrable_of_hasCompactSupport hsupp.mul_left
    simp only [Pi.add_apply, add_mul]
    rw [integral_add hxi hyi, hx, hy, add_zero]
  | smul a x _ hx =>
    simp only [Pi.smul_apply, smul_eq_mul, mul_assoc]
    rw [integral_const_mul, hx, mul_zero]

/-! ### The determinacy theorem -/

/-- **Moment determinacy.** A continuous compactly supported `f : ℝⁿ → ℝ` with
`∫ xᵛ f = 0` for every monomial `xᵛ` is identically zero. -/
theorem eq_zero_of_integral_monomialTest_mul_eq_zero {f : EuclidD n → ℝ} (hf : Continuous f)
    (hsupp : HasCompactSupport f)
    (h : ∀ (k : ℕ) (w : Fin k → Fin n), ∫ y, monomialTest w y * f y = 0) : f = 0 := by
  classical
  set K : Set (EuclidD n) := tsupport f with hK
  have : CompactSpace K := isCompact_iff_compactSpace.mp hsupp
  let coordK : Fin n → C(K, ℝ) := fun i ↦
    ⟨fun y ↦ (y : EuclidD n) i,
      (PiLp.continuous_apply 2 (fun _ : Fin n ↦ ℝ) i).comp continuous_subtype_val⟩
  let A : Subalgebra ℝ C(K, ℝ) := Algebra.adjoin ℝ (Set.range coordK)
  have hsep : A.SeparatesPoints := by
    intro y y' hyy'
    have hex : ∃ i, (y : EuclidD n) i ≠ (y' : EuclidD n) i := by
      by_contra hcon
      push Not at hcon
      exact hyy' (Subtype.ext (PiLp.ext hcon))
    obtain ⟨i, hi⟩ := hex
    exact ⟨coordK i, ⟨coordK i, Algebra.subset_adjoin (Set.mem_range_self i), rfl⟩, hi⟩
  -- every element of `A` is the restriction of a polynomial
  have hA : ∀ g ∈ A, ∃ P ∈ polySpan n, ∀ y : K, g y = P y := by
    intro g hg
    induction hg using Algebra.adjoin_induction with
    | mem x hx =>
      obtain ⟨i, rfl⟩ := hx
      exact ⟨monomialTest ![i], monomialTest_mem_polySpan _,
        fun y ↦ by simp [coordK, monomialTest]⟩
    | algebraMap r =>
      refine ⟨fun _ ↦ r, ?_, fun y ↦ by simp⟩
      have hr : (fun _ : EuclidD n ↦ r) = r • monomialTest (Fin.elim0 : Fin 0 → Fin n) := by
        funext x
        simp [monomialTest]
      rw [hr]
      exact Submodule.smul_mem _ _ (monomialTest_mem_polySpan _)
    | add x y _ _ hx hy =>
      obtain ⟨P, hP, hPx⟩ := hx
      obtain ⟨Q, hQ, hQy⟩ := hy
      exact ⟨P + Q, Submodule.add_mem _ hP hQ, fun z ↦ by simp [hPx z, hQy z]⟩
    | mul x y _ _ hx hy =>
      obtain ⟨P, hP, hPx⟩ := hx
      obtain ⟨Q, hQ, hQy⟩ := hy
      exact ⟨P * Q, polySpan_mul_mem hP hQ, fun z ↦ by simp [hPx z, hQy z]⟩
  let fK : C(K, ℝ) := ⟨fun y ↦ f y, hf.comp continuous_subtype_val⟩
  have hint : Integrable (fun y ↦ f y * f y) :=
    (hf.mul hf).integrable_of_hasCompactSupport hsupp.mul_left
  have hfi : Integrable f := hf.integrable_of_hasCompactSupport hsupp
  have habs : Integrable (fun y ↦ |f y|) := hfi.abs
  -- `∫ f² ≤ ε ∫ |f|` for every `ε > 0`
  have hle : ∀ ε > 0, ∫ y, f y * f y ≤ ε * ∫ y, |f y| := by
    intro ε hε
    obtain ⟨g, hg⟩ :=
      ContinuousMap.exists_mem_subalgebra_near_continuousMap_of_separatesPoints A hsep fK ε hε
    obtain ⟨P, hP, hPg⟩ := hA g g.2
    have hPf : ∫ y, P y * f y = 0 := integral_mul_eq_zero_of_mem_polySpan hf hsupp h hP
    have hPc : Continuous P := continuous_of_mem_polySpan hP
    have hPi : Integrable (fun y ↦ P y * f y) :=
      (hPc.mul hf).integrable_of_hasCompactSupport hsupp.mul_left
    have hpt : ∀ y, f y * f y - P y * f y ≤ ε * |f y| := by
      intro y
      by_cases hy : y ∈ K
      · have hb : |(g : C(K, ℝ)) ⟨y, hy⟩ - fK ⟨y, hy⟩| ≤ ‖(g : C(K, ℝ)) - fK‖ := by
          have := ContinuousMap.norm_coe_le_norm ((g : C(K, ℝ)) - fK) ⟨y, hy⟩
          simpa [Real.norm_eq_abs] using this
        have hb' : |P y - f y| < ε := by
          have h1 : (g : C(K, ℝ)) ⟨y, hy⟩ = P y := hPg ⟨y, hy⟩
          have h2 : fK ⟨y, hy⟩ = f y := rfl
          rw [h1, h2] at hb
          exact lt_of_le_of_lt hb hg
        calc f y * f y - P y * f y = f y * (f y - P y) := by ring
          _ ≤ |f y * (f y - P y)| := le_abs_self _
          _ = |f y| * |f y - P y| := abs_mul _ _
          _ ≤ |f y| * ε := by
              apply mul_le_mul_of_nonneg_left _ (abs_nonneg _)
              rw [abs_sub_comm]
              exact hb'.le
          _ = ε * |f y| := mul_comm _ _
      · have hfy : f y = 0 := image_eq_zero_of_notMem_tsupport hy
        simp [hfy]
    calc ∫ y, f y * f y = ∫ y, (f y * f y - P y * f y) := by
          rw [integral_sub hint hPi, hPf, sub_zero]
      _ ≤ ∫ y, ε * |f y| := integral_mono (hint.sub hPi) (habs.const_mul ε) hpt
      _ = ε * ∫ y, |f y| := integral_const_mul _ _
  have hsq0 : ∫ y, f y * f y = 0 := by
    set I := ∫ y, f y * f y with hI
    set C := ∫ y, |f y| with hC
    have hC0 : 0 ≤ C := integral_nonneg fun y ↦ abs_nonneg _
    have hI0 : 0 ≤ I := integral_nonneg fun y ↦ mul_self_nonneg _
    refine le_antisymm ?_ hI0
    by_contra hpos
    push Not at hpos
    have hε := hle (I / (2 * (C + 1))) (by positivity)
    have key : I / (2 * (C + 1)) * C < I := by
      rw [div_mul_eq_mul_div, div_lt_iff₀ (by positivity)]
      nlinarith
    linarith
  have hae : (fun y ↦ f y * f y) =ᵐ[volume] 0 :=
    (integral_eq_zero_iff_of_nonneg (fun y ↦ mul_self_nonneg (f y)) hint).mp hsq0
  have heq : (fun y ↦ f y * f y) = 0 := ((hf.mul hf).ae_eq_iff_eq volume continuous_const).mp hae
  funext y
  have := congrFun heq y
  simp only [Pi.zero_apply] at this
  exact mul_self_eq_zero.mp this

end Laplace.Multi
