/-
Copyright (c) 2026 Timaeus. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Timaeus
-/
import Mathlib
import Laplace.Multi.TargetPythagoras
import Laplace.Multi.ObservableCurvature

/-!
# The exact observable defect of the atlas

Every reconstructed law `Π(N)` (interior `N`) has a `σ(S)`-measurable density with respect to `ν`, s
                                        o
for a bounded observable `φ` with conditional expectation `ψ = E_ν[φ | σ(S)]`,

  `E_{Π(N)} φ = E_{Π(N)} ψ`                    (`integral_responseProjection_condExp`).

Along the bridge `D_s = aν + bD` (response `M_s = a m₀ + b M_D`), the gap between the actual and the
projected expectation of `φ` splits exactly into a fibre part, linear in the mixing weight, and a
statistic-law part that depends on `φ` only through `ψ`:

  `E_{D_s} φ − E_{Π(M_s)} φ = b (E_D φ − E_D ψ) + (E_{D_s} ψ − E_{Π(M_s)} ψ)`
                                                            (`observableDefect_eq`).

On the atlas path the defect is differentiable, with

  `Δ_φ'(s) = E_D φ − E_ν φ + Cov_{Π(M_s)}(φ, ⟨v_s, S⟩)`     (`hasDerivAt_observableDefect`),

where `v_s = θ_s'` is the velocity of the natural coordinates: the actual response of `φ` to the dat
                                        a
is linear, the projected response is the covariance with the moving direction, and their difference
at `s = 0` is the susceptibility defect of first-order mean reconstruction.
-/

open MeasureTheory Filter Topology Set InformationTheory
open scoped ENNReal NNReal

namespace Laplace.Multi

set_option warn.classDefReducibility false in
/-- The σ-algebra generated by the statistic. -/
def statSigma {X : Type*} {J : Type*} (S : J → X → ℝ) : MeasurableSpace X :=
  MeasurableSpace.comap (statPoint S) MeasurableSpace.pi

section Conditional

variable {X : Type*} [MeasurableSpace X] {J : Type*} {S : J → X → ℝ}
  (hS : ∀ j, Bdd (S j)) (ν : Measure X) [IsProbabilityMeasure ν]
include hS

omit [IsProbabilityMeasure ν] in
theorem statSigma_le : statSigma S ≤ ‹MeasurableSpace X› :=
  measurable_iff_comap_le.1 (measurable_statPoint hS)

/-- A bounded `σ(S)`-measurable weight passes through the conditional expectation. -/
theorem integral_mul_condExp_statSigma {φ : X → ℝ} (hφ : Bdd φ) {g : X → ℝ}
    (hg : StronglyMeasurable[statSigma S] g) {c : ℝ} (hgc : ∀ x, |g x| ≤ c) :
    ∫ x, g x * φ x ∂ν = ∫ x, g x * (ν[φ | statSigma S]) x ∂ν := by
  have hm := statSigma_le hS
  have h := condExp_stronglyMeasurable_mul_of_bound hm hg (integrable_of_bdd_prob ν hφ) c
    (Eventually.of_forall fun x ↦ by rw [Real.norm_eq_abs]; exact hgc x)
  have h1 : ∫ x, (ν[g * φ | statSigma S]) x ∂ν = ∫ x, (g * φ) x ∂ν := integral_condExp hm
  simp only [Pi.mul_apply] at h1
  rw [← h1, integral_congr_ae h]
  simp only [Pi.mul_apply]

/-- Under a bounded tilt by an affine function of the statistic, `E φ = E ψ`. -/
theorem integral_tilted_dirLoss_condExp [Fintype J] {φ : X → ℝ} (hφ : Bdd φ) (θ : J → ℝ) :
    ∫ x, φ x ∂(ν.tilted fun x ↦ -1 * dirLoss S θ x) =
      ∫ x, (ν[φ | statSigma S]) x ∂(ν.tilted fun x ↦ -1 * dirLoss S θ x) := by
  rw [integral_tilted, integral_tilted]
  simp only [smul_eq_mul]
  obtain ⟨B, hB⟩ : ∃ B, ∀ x, |dirLoss S θ x| ≤ B := (bdd_dirLoss hS θ).2
  have hZ : 0 < ∫ x, Real.exp (-1 * dirLoss S θ x) ∂ν :=
    integral_exp_pos (integrable_exp_of_bdd ν (Bdd.const_mul (-1) (bdd_dirLoss hS θ)))
  have hmeas : StronglyMeasurable[statSigma S] fun x ↦
      Real.exp (-1 * dirLoss S θ x) / ∫ x, Real.exp (-1 * dirLoss S θ x) ∂ν := by
    have h1 : Measurable[statSigma S] (statPoint S) := comap_measurable _
    have hc : Continuous fun y : J → ℝ ↦ dotJ θ y := by
      simp only [dotJ]
      fun_prop
    have h2 : Measurable[statSigma S] fun x ↦ dirLoss S θ x := by
      have e : (fun x ↦ dirLoss S θ x) = (fun y ↦ dotJ θ y) ∘ statPoint S := by
        funext x
        simp only [Function.comp, dirLoss, dotJ, statPoint]
      rw [e]
      exact hc.measurable.comp h1
    exact ((h2.const_mul (-1)).exp.div_const _).stronglyMeasurable
  refine integral_mul_condExp_statSigma hS ν hφ hmeas
    (c := Real.exp B / ∫ x, Real.exp (-1 * dirLoss S θ x) ∂ν) fun x ↦ ?_
  rw [abs_div, abs_of_pos hZ, abs_of_pos (Real.exp_pos _)]
  refine div_le_div_of_nonneg_right ?_ hZ.le
  refine Real.exp_le_exp.2 ?_
  have := (abs_le.1 (hB x)).1
  linarith

omit hS [IsProbabilityMeasure ν] in
/-- The mixture integral of an integrable observable. -/
theorem integral_mixture_of_integrable (ρ : Measure X) {φ : X → ℝ} (hν : Integrable φ ν)
    (hρ : Integrable φ ρ) (a b : ℝ≥0) :
    ∫ x, φ x ∂(a • ν + b • ρ) = a * ∫ x, φ x ∂ν + b * ∫ x, φ x ∂ρ := by
  have h1 : Integrable φ (a • ν) := hν.smul_measure ENNReal.coe_ne_top
  have h2 : Integrable φ (b • ρ) := hρ.smul_measure ENNReal.coe_ne_top
  rw [integral_add_measure h1 h2, integral_smul_nnreal_measure, integral_smul_nnreal_measure,
    NNReal.smul_def, NNReal.smul_def, smul_eq_mul, smul_eq_mul]

omit [IsProbabilityMeasure ν] in
/-- The conditional expectation of a bounded observable is integrable under every `D ≪ ν`. -/
theorem integrable_condExp_of_ac {φ : X → ℝ} (hφ : Bdd φ) (D : Measure X) [IsFiniteMeasure D]
    (hDν : D ≪ ν) : Integrable (ν[φ | statSigma S]) D := by
  obtain ⟨-, B, hB⟩ := hφ
  have hae : ∀ᵐ x ∂ν, |(ν[φ | statSigma S]) x| ≤ B :=
    ae_bdd_abs_condExp_of_ae_bdd_abs (Eventually.of_forall hB)
  refine Integrable.of_bound
    ((stronglyMeasurable_condExp.mono (statSigma_le hS)).aestronglyMeasurable) B ?_
  filter_upwards [hDν.ae_le hae] with x hx
  rw [Real.norm_eq_abs]
  exact hx

end Conditional

section Defect

variable {X : Type*} [MeasurableSpace X] [Nonempty X] {J : Type*} [Fintype J] [Nonempty J]
  {S : J → X → ℝ} (hS : ∀ j, Bdd (S j)) (ν : Measure X) [IsProbabilityMeasure ν]
include hS

/-- **Reconstructed laws see only the conditional expectation**: `E_{Π(N)} φ = E_{Π(N)} ψ`. -/
theorem integral_responseProjection_condExp {φ : X → ℝ} (hφ : Bdd φ) {N : J → ℝ}
    (hrel : N ∈ intrinsicInterior ℝ (momentBody ν (fun _ ↦ (1 : ℝ)) S)) :
    ∫ x, φ x ∂responseProjection hS ν N =
      ∫ x, (ν[φ | statSigma S]) x ∂responseProjection hS ν N := by
  rw [responseProjection_eq_familyMeasure_responseTheta hS ν hrel,
    familyMeasure_one_zero_eq_tilted hS ν]
  exact integral_tilted_dirLoss_condExp hS ν hφ _

/-- **The exact observable defect along the bridge**:
`E_{D_s} φ − E_{Π(M_s)} φ = b (E_D φ − E_D ψ) + (E_{D_s} ψ − E_{Π(M_s)} ψ)`. -/
theorem observableDefect_eq (D : Measure X) [IsProbabilityMeasure D] (hDν : D ≪ ν) {φ : X → ℝ}
    (hφ : Bdd φ)
    {a b : ℝ≥0}
    (hrel : ((a : ℝ) • (fun i ↦ ∫ x, S i x ∂ν) + (b : ℝ) • fun i ↦ ∫ x, S i x ∂D) ∈
      intrinsicInterior ℝ (momentBody ν (fun _ ↦ (1 : ℝ)) S)) :
    (∫ x, φ x ∂(a • ν + b • D)) - ∫ x, φ x ∂responseProjection hS ν
        ((a : ℝ) • (fun i ↦ ∫ x, S i x ∂ν) + (b : ℝ) • fun i ↦ ∫ x, S i x ∂D) =
      b * ((∫ x, φ x ∂D) - ∫ x, (ν[φ | statSigma S]) x ∂D) +
        ((∫ x, (ν[φ | statSigma S]) x ∂(a • ν + b • D)) -
          ∫ x, (ν[φ | statSigma S]) x ∂responseProjection hS ν
            ((a : ℝ) • (fun i ↦ ∫ x, S i x ∂ν) + (b : ℝ) • fun i ↦ ∫ x, S i x ∂D)) := by
  rw [integral_responseProjection_condExp hS ν hφ hrel,
    integral_mixture_of_integrable ν D (integrable_of_bdd_prob ν hφ) (integrable_of_bdd_prob D hφ),
    integral_mixture_of_integrable ν D integrable_condExp (integrable_condExp_of_ac hS ν hφ D hDν),
    integral_condExp (statSigma_le hS)]
  ring

/-- **The derivative of the observable defect along the atlas path**:
`Δ_φ'(s) = E_D φ − E_ν φ + Cov_{Π(M_s)}(φ, ⟨v_s, S⟩)`. -/
theorem hasDerivAt_observableDefect (D : Measure X) [IsProbabilityMeasure D]
    (hfin : genRate ν S (fun i ↦ ∫ x, S i x ∂D) ≠ ⊤) {φ : X → ℝ} (hφ : Bdd φ) {s : ℝ}
    (hs0 : 0 ≤ s) (hs1 : s < 1) :
    HasDerivAt (fun s ↦ (1 - s) * (∫ x, φ x ∂ν) + s * (∫ x, φ x ∂D) -
        ∫ x, φ x ∂familyMeasure ν (fun _ ↦ (1 : ℝ)) (fun _ ↦ (0 : ℝ)) S 1
          (atlasTheta hS ν (fun i ↦ ∫ x, S i x ∂D) s))
      ((∫ x, φ x ∂D) - (∫ x, φ x ∂ν) +
        lawCov (familyMeasure ν (fun _ ↦ (1 : ℝ)) (fun _ ↦ (0 : ℝ)) S 1
          (atlasTheta hS ν (fun i ↦ ∫ x, S i x ∂D) s)) φ (dirLoss S (atlasVel hS ν hfin s))) s := by
  have h1 : HasDerivAt (fun s : ℝ ↦ (1 - s) * (∫ x, φ x ∂ν) + s * (∫ x, φ x ∂D))
      ((∫ x, φ x ∂D) - ∫ x, φ x ∂ν) s := by
    have := (((hasDerivAt_const s (1 : ℝ)).sub (hasDerivAt_id' (x := s))).mul_const
      (∫ x, φ x ∂ν)).add ((hasDerivAt_id' (x := s)).mul_const (∫ x, φ x ∂D))
    refine this.congr_deriv ?_
    ring
  have h2 := hasDerivAt_integral_familyMeasure_atlas hS ν hfin hs0 hs1 hφ
  refine (h1.sub h2).congr_deriv ?_
  ring

end Defect

end Laplace.Multi
