/-
Copyright (c) 2026 Timaeus. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Timaeus
-/
import Mathlib
import Laplace.Multi.TiltRateQuadratic

/-!
# The projection defect along a tilt is the energy of the residual score

Combining the two quadratic expansions: along the tilts `ν_t ∝ e^{tf} ν`, with `h = f − E_ν f`
the centred score and `B₀` the projection onto the affine span of the statistic in `L²(ν)`,

  `KL(ν_t ‖ Π(M_t)) / t² → ‖h − B₀ h‖² / 2`
                                        (`tendsto_klDiv_tilt_responseProjection_div_sq`).

Together with `KL(ν_t ‖ ν)/t² → ‖h‖²/2` and `𝓘(M_t)/t² → ‖B₀ h‖²/2`, this is the quadratic shadow of
the Pythagorean identity `KL(D ‖ ν) = 𝓘(M_D) + KL(D ‖ Π(M_D))`: to second order, the information
generated by an infinitesimal change of the law splits into the energy of the projected score
(visible to the atlas) and the energy of the residual score (the projection defect).
-/

open MeasureTheory Filter Topology Set InformationTheory
open scoped ENNReal

namespace Laplace.Multi

variable {X : Type*} [MeasurableSpace X] [Nonempty X] {J : Type*} [Fintype J] [Nonempty J]
  {S : J → X → ℝ} (hS : ∀ j, Bdd (S j)) (ν : Measure X) [IsProbabilityMeasure ν]
include hS

omit [Nonempty X] [Nonempty J] in
/-- **Pythagoras in `L²(ν)` for the centred score**: `‖h − B₀h‖² = Var_ν f − ⟨a, u⟩`, with `a` the
regression coefficient and `u = Cov_ν(S, f)`. -/
theorem norm_sq_sub_starProjection_statSpan {f : X → ℝ} (hf : Bdd f) {a : J → ℝ}
    (hreg : ∀ j, lawCov ν (S j) (dirLoss S a) = lawCov ν (S j) f) :
    ‖((memLp_two_bdd ν hf).toLp f - (∫ x, f x ∂ν) • oneLp ν) -
        (statSpan hS ν).starProjection
          ((memLp_two_bdd ν hf).toLp f - (∫ x, f x ∂ν) • oneLp ν)‖ ^ 2 =
      lawCov ν f f - dotJ a (fun j ↦ lawCov ν (S j) f) := by
  obtain ⟨h, hh⟩ : ∃ h : Lp ℝ 2 ν, h = (memLp_two_bdd ν hf).toLp f - (∫ x, f x ∂ν) • oneLp ν :=
    ⟨_, rfl⟩
  have hpyth := Submodule.norm_sq_eq_add_norm_sq_starProjection h (statSpan hS ν)
  rw [Submodule.starProjection_orthogonal_val] at hpyth
  have hB : (statSpan hS ν).starProjection h = regressionLp hS ν a f - (∫ x, f x ∂ν) • oneLp ν := by
    rw [hh, map_sub, map_smul, starProjection_statSpan_toLp hS ν hf hreg,
      Submodule.starProjection_eq_self_iff.2 (oneLp_mem_statSpan hS ν)]
  rw [hB, norm_sq_regressionLp_sub_eq_dotJ hS ν hreg] at hpyth
  rw [← hh, hB]
  have hvar := norm_sq_toLp_sub_mean ν hf
  rw [← hh] at hvar
  linarith

/-- Pythagoras for the tilt: `KL(ν_t ‖ ν) = 𝓘(M_t) + KL(ν_t ‖ Π(M_t))`. -/
theorem klDiv_tilt_eq_genRate_add {f : X → ℝ} (hf : Bdd f) (t : ℝ) :
    (klDiv (ν.tilted fun x ↦ t * f x) ν).toReal =
      (genRate ν S (tiltResponse S ν f t)).toReal +
        (klDiv (ν.tilted fun x ↦ t * f x)
          (responseProjection hS ν (tiltResponse S ν f t))).toReal := by
  have := isProbabilityMeasure_tilted (integrable_exp_of_bdd ν (Bdd.const_mul t hf))
  have hfin := genRate_tiltResponse_ne_top hS ν hf t
  obtain ⟨-, -, -, hpyth⟩ := responseProjection_spec hS ν hfin
  have h := hpyth (ν.tilted fun x ↦ t * f x) inferInstance rfl
  have hkl : klDiv (ν.tilted fun x ↦ t * f x) ν ≠ ⊤ := by
    rw [klDiv_tilted_eq ν (Bdd.const_mul t hf)]
    exact ENNReal.ofReal_ne_top
  have hne : klDiv (ν.tilted fun x ↦ t * f x)
      (responseProjection hS ν (tiltResponse S ν f t)) ≠ ⊤ := by
    intro htop
    rw [htop, top_add] at h
    exact hkl h
  rw [h, ENNReal.toReal_add hne hfin]
  ring

/-- **The projection defect along a tilt is the energy of the residual score**:
`KL(ν_t ‖ Π(M_t)) / t² → ‖h − B₀ h‖² / 2` with `h = f − E_ν f`. -/
theorem tendsto_klDiv_tilt_responseProjection_div_sq {f : X → ℝ} (hf : Bdd f) :
    Tendsto (fun t ↦ (klDiv (ν.tilted fun x ↦ t * f x)
        (responseProjection hS ν (tiltResponse S ν f t))).toReal / t ^ 2) (𝓝[≠] 0)
      (𝓝 (‖((memLp_two_bdd ν hf).toLp f - (∫ x, f x ∂ν) • oneLp ν) -
        (statSpan hS ν).starProjection
          ((memLp_two_bdd ν hf).toLp f - (∫ x, f x ∂ν) • oneLp ν)‖ ^ 2 / 2)) := by
  obtain ⟨a, -, hreg, hI⟩ := tendsto_genRate_tiltResponse_div_sq hS ν hf
  rw [norm_sq_sub_starProjection_statSpan hS ν hf hreg]
  have hK := tendsto_klDiv_tilted_div_sq ν hf
  have h := hK.sub hI
  have e : (lawCov ν f f - dotJ a fun j ↦ lawCov ν (S j) f) / 2 =
      lawCov ν f f / 2 - (dotJ a fun j ↦ lawCov ν (S j) f) / 2 := by ring
  rw [e]
  refine h.congr fun t ↦ ?_
  rw [klDiv_tilt_eq_genRate_add hS ν hf t, add_div]
  ring

end Laplace.Multi
